### ISSUE TITLE
Danke!

### ISSUE THREAD

**Issue by kohlsalem** [stecklars/dynamic-dns-netcup-api#18]
Hallo, 

Wenn ich mir überlege, was für Stunts ich machen wollte um ein DYNDNS auf netcup nachzubilden - bevor ich über dieses repo gestolpert bin - wollte ich einfach mal DANKE sagen.

Hat sofort funktioniert!

Gruß
Michael

**Comment by stecklars** [comment]
Hallo @kohlsalem,


vielen Dank für deine sehr netten Worte.

Es freut mich, dass dir das Skript helfen konnte :)


Viele Grüße
Lars
