### ISSUE TITLE
Question about execution schedule

### ISSUE THREAD

**Issue by OevreFlataeker** [stecklars/dynamic-dns-netcup-api#19]
Dear Lars,

I have a question about the scheduled execution of the script:
You mention in the README:

```
Missing

Caching the IP provided to netcup DNS, to avoid running into (currently extremely tolerant) rate limits in the DNS API

```
but recommend to run it every couple of minutes.
If the script detects that there was NO IP change (i.e. normally only once a day on enforced DSL reconnection), will it utilize the API to update the record (to the same value) or will it just skip it? In other words, whats a tolerable execution period to not spam the netcup API with unnecessary requests?

Your script is very helpful, thanks a lot!

**Comment by Copro** [comment]
The current recommendation in the [how-to-use section](https://github.com/stecklars/dynamic-dns-netcup-api#how-to-use) is to use the script every 5 minutes (which matches the default behavior of setting the TTL to 300 seconds. 
"Add it to your cronjobs and run it regularly, for example every five minutes."

There is a pull request open to cache or store the IPv4 and IPv6 addresses locally before making the requests:
https://github.com/stecklars/dynamic-dns-netcup-api/pull/13

**Comment by stecklars** [comment]
Honestly, with the current netcup API rate limits, you would probably have no issues running it every minute. I personally recommend running it every five minutes, as stated in the readme file.
