### ISSUE TITLE
API didn't return a valid IPv4 addres

### ISSUE THREAD

**Issue by kinoegit** [stecklars/dynamic-dns-netcup-api#22]
Hi Lars, by the way: thanks for this great and helpful tool!
Since this morning running update.php throws following error:
```
php /home/johndoe/dynamic-dns-netcup-api/update.php                                  [2022/10/22 07:45:45 +0200][NOTICE] =============================================
[2022/10/22 07:45:45 +0200][NOTICE] Running dynamic DNS client for netcup 3.0
[2022/10/22 07:45:45 +0200][NOTICE] This script is not affiliated with netcup.
[2022/10/22 07:45:45 +0200][NOTICE] =============================================

PHP Warning:  file_get_contents(): Peer certificate CN=`johndoe.de' did not match expected CN=`api.ipify.org' in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 142
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 142
PHP Warning:  file_get_contents(https://api.ipify.org): Failed to open stream: operation failed in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 142
[2022/10/22 07:45:45 +0200][WARNING] https://api.ipify.org didn't return a valid IPv4 address. Trying fallback API https://ip4.seeip.org
PHP Warning:  file_get_contents(): Peer certificate CN=`johndoe.de' did not match expected CN=`ip4.seeip.org' in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 152
PHP Warning:  file_get_contents(): Failed to enable crypto in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 152
PHP Warning:  file_get_contents(https://ip4.seeip.org): Failed to open stream: operation failed in /home/johndoe/dynamic-dns-netcup-api/functions.php on line 152
[2022/10/22 07:45:45 +0200][ERROR] Main API and fallback API didn't return a valid IPv4 address. Exiting.
```

Checking https://www.ipify.org/ it seems that their API URL changed from https://**api**.ipify.org to https://**api64**.ipify.org.
So I modified functions.php on line 142 accordingly from:
`    $publicIP = rtrim(file_get_contents('https://api.ipify.org'));`
to
`    $publicIP = rtrim(file_get_contents('https://api64.ipify.org'));`
and the update ran fine again!

As you see I'm still using version 3.0, but there is still the old Api URL in functions.php of the latest release (v 3.0.1)

**Comment by Stephan2612** [comment]
Hello Lars, 
same error here.
Changing 
$publicIP = rtrim(file_get_contents('https://api.ipify.org'));
to
$publicIP = rtrim(file_get_contents('https://api64.ipify.org'));
is unsuccessfull.

Any idea?

**Comment by killerbees19** [comment]
@Stephan2612 Please post full error message.

And don't use `api64`…
* api4.ipify.org: IPv4 only
* api6.ipify.org: IPv6 only
* api64.ipify.org: IPv4/IPv6 dual stack

Anyways, I'm unable to reproduce the errors while trying to fetch these URLs with cURL. (And with different/empty `--user-agent` values.)

**Comment by kinoegit** [comment]
![Screenshot_20221029_232450](https://user-images.githubusercontent.com/18682867/198853689-9f60f660-61d7-48df-abb5-eda91ed60b11.png)
As you see cURL https://api.ipify.org doesn't do the job

**Comment by Stephan2612** [comment]
@killerbees19 
my full error message has looked exactly like that of kinoegit (of course with other domainnames ;)

Meanwhile, I have found the error, although I am wondering how it can happen while I am on holiday and no one has changed any configuration: Pi-hole was blocking api.ipify.org and ip4.seeip.org.  Why? I don´t know.

Thank you, killerbees19, for your offer of help.

**Comment by kinoegit** [comment]
@Stephan2612
thanks, you're right! same here: AdGuard blocked https://api.ipify.org/. Seems to be a new and false entry in AdGuards DNS filterlist I reckon. 
Issue solved
