### ISSUE TITLE
SeeIP changed URL's

### ISSUE THREAD

**Issue by hpreusse** [stecklars/dynamic-dns-netcup-api#26]
Maybe the issue is related to #21 . I just noticed that seeip changed the URL's to read out the IPv4 / IPv6 addresses. They now read https://ipv4.seeip.org & https://ipv6.seeip.org. I noticed the messages:

[2023/01/25 08:16:02 +0100][WARNING] https://ip6.seeip.org didn't return a valid IPv6 address.

in the log, which are gone after fixing the URL in functions.php. Thanks for your work!

**Comment by hpreusse** [comment]
I've created #27 for this issue.

**Comment by stecklars** [comment]
Closed via #27.
