### ISSUE TITLE
query IPv4 directly from Fritzbox if available

### ISSUE THREAD

**Issue by dbielz** [stecklars/dynamic-dns-netcup-api#28]
Queries for IPv4 via _api.ipify.org_ and for IPv6 via _seeip.org_ often take some time since this service seems to be frequented very much, so I searched for an alternative. As an owner of a fritzbox router, I knew, that there should be some way to query this information directly. I found a solution here: **https://wiki.ubuntuusers.de/FritzBox/Skripte/** , where **variant 2** worked very well on my bash (Ubuntu 22.04 server behind fritzbox in cable network; assigning public ip4 ordered as option). Maybe we could take some load off the services api.ipify.org and seeip.org.

For IPv6 you will have to use the IP address of the host, since IPv6 does not use translation (i don't remember the correct term right now). Here I use the basic commands 
`hostname -I | cut -d " " -f 3` ( in my case it's f 3, in others it might be f 2) 
Another way to deal with multiple IPv6 addresses could be to filter out those starting with 'fd00' and 'fe80' since they are only local.

Unfortunately I have no php-skills, otherwise I would try to include these options into the functions.php. For now I use two little bash scripts when invoking './update'

Maybe we could help to take some load off the services api.ipify.org and seeip.org.

**Comment by stecklars** [comment]
Hi,

Thank you for using my script and your suggestion.

I have changed the default API for determining the public IPv4 / IPv6 address to my own in the latest version now, so this should work better (hopefully).

I currently do not plan to integrate any device specific ways to get the IP address information, as this is out of scope for this project in my opinion. That being said, feel free to use the script in this way, as you can pass the information using the options when running it (like you already do).
