### ISSUE TITLE
error accessing api.ipify.org

### ISSUE THREAD

**Issue by Chavell3** [stecklars/dynamic-dns-netcup-api#30]
Hi,

It seems there is an issue accessing https://api.ipify.org...
When I execute the script, I get a message:

"cURL Error while accessing https://api.ipify.org/: (7) Failed to connect to api.ipify.org port 443: Connection refused - Retrying in 30 seconds."

even trying to access ipify.org from a browser is not possible.
Does somebody know what the issue of that is, and how to solve it?

Thanks!

**Comment by stecklars** [comment]
Hi,

thank you for using my script.

It seems that for some reason, ipify (temporarily?) blocked you from using their API.

In the newest version of my script, my very own API for determining the public IPv4 / IPv6 address is used, so this shouldn't be an issue anymore. In any case, the script will also try a fallback API in case the first API is not reachable / returns an invalid result after three tries.
