### ISSUE TITLE
Cronjob throwing PHP Warnings and can't login

### ISSUE THREAD

**Issue by ornago** [stecklars/dynamic-dns-netcup-api#8]
I'm using a cronjob to trigger your update.php and having problems since a few days

/etc/cron.d/netcup
```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

*/5 * * * * root /usr/bin/php -f /opt/dynamic-dns-netcup-api/******/update.php  > /var/log/netcup.log 2>&1
```

/var/log/netcup.log
```
PHP Warning:  Use of undefined constant HOST - assumed 'HOST' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/update.php on line 11
PHP Warning:  Use of undefined constant DOMAIN - assumed 'DOMAIN' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/update.php on line 11
[2021/01/22 11:40:01 +0100][NOTICE] Updating DNS records for host HOST on domain DOMAIN

PHP Warning:  Use of undefined constant CUSTOMERNR - assumed 'CUSTOMERNR' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/update.php on line 14
PHP Warning:  Use of undefined constant APIKEY - assumed 'APIKEY' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/update.php on line 14
PHP Warning:  Use of undefined constant APIPASSWORD - assumed 'APIPASSWORD' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/update.php on line 14
PHP Warning:  Use of undefined constant APIURL - assumed 'APIURL' (this will throw an Error in a future version of PHP) in /opt/dynamic-dns-netcup-api/******/functions.php on line 20
PHP Notice:  Trying to access array offset on value of type null in /opt/dynamic-dns-netcup-api/******/functions.php on line 133
PHP Notice:  Trying to access array offset on value of type null in /opt/dynamic-dns-netcup-api/******/functions.php on line 137
[2021/01/22 11:40:01 +0100][ERROR] Error while logging in:  Exiting.
```

Already tried to change update.php and functions.php with the 'assumed' changes from PHP Notice. Returned into:
```
PHP Notice:  Trying to access array offset on value of type null in /opt/dynamic-dns-netcup-api/******/functions.php on line 133
PHP Notice:  Trying to access array offset on value of type null in /opt/dynamic-dns-netcup-api/******/functions.php on line 137
[2021/01/22 11:40:01 +0100][ERROR] Error while logging in:  Exiting.
```

However, when I start the process by myself in a shell, it runs without any problem.
PHP Version 7.4 (tried 7.2 too)
Debian 10 (Buster)

**Comment by Hecke29** [comment]
Please be sure the `config.php` on the machine contains definitions of the mentioned constants (e.g. `HOST` and `DOMAIN`). 
There has been a refactoring a few days ago where a `config.dist.php` was introduced and the `config.php` was added to `.gitignore` - maybe this affects you?

In doubt please post the contents of the `config.php` removing sensible data.

Edit:

> However, when I start the process by myself in a shell, it runs without any problem.

Seems to be an issue with relative loading paths. Try changing the directory to `/opt/dynamic-dns-netcup-api/******/` before running `update.php`. Thus
```
*/5 * * * * root cd /opt/dynamic-dns-netcup-api/******/ && /usr/bin/php update.php  > /var/log/netcup.log 2>&1
```
could do the trick.

**Comment by ornago** [comment]
Thanks for your comment and the "trick" to solve my problem fast.
My installation of the script was from 2019 and worked normally till the beginning of last week. Did the update with "git pull" yesterday, but it didn't helped anyway.

My config.php is filled with all the information needed.

Changing the path before starting really helped to get it working again, thank you very much.
Gonna close it but please be aware of the PHP Warning,
